### ISSUE TITLE
Dashboard GAE deployment issue: import _regex ImportError: dynamic module does not define init function (init_regex)

### ISSUE THREAD

**Issue by crushallhumans** [duo-labs/isthislegit#1]
I might be making a newbie GAE mistake here, but the following error persists on my attempt to load the dashboard app. Googling the eventual error message yields a lot of data on how to correctly compile Python down to C, but I'm thinking that isn't what's going on here. Any ideas?

`
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/isthislegit.py", line 1, in <module>
    from app.report import report_blueprint
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/app/report.py", line 2, in <module>
    from flanker.addresslib import address
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/flanker/addresslib/address.py", line 38, in <module>
    import flanker.addresslib.parser
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/flanker/addresslib/parser.py", line 79, in <module>
    from flanker.mime.message.headers.encoding import encode_string
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/flanker/mime/__init__.py", line 62, in <module>
    from flanker.mime.message.errors import DecodingError, EncodingError, MimeError
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/flanker/mime/message/__init__.py", line 1, in <module>
    from flanker.mime.message.scanner import ContentType
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/flanker/mime/message/scanner.py", line 1, in <module>
    import regex as re
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/regex.py", line 387, in <module>
    import _regex_core
  File "/base/data/home/apps/p~splash-internal-isthislegit/20170726t185028.402951000175401845/lib/_regex_core.py", line 21, in <module>
    import _regex
ImportError: dynamic module does not define init function (init_regex)
`

**Comment by jordan-wright** [comment]
Hey there!

This is expected but still a pain that I'm really sorry you're having to deal with.

Google App Engine struggles with using third party libraries with C bindings. The library we use for mail parsing, "flanker" uses some libraries that would be included here.

Fortunately, we have some workarounds available. I have docs that I'll upload this evening but in a nutshell you'll want to replace every instance of "import regex" in the lib/flanker folder with "import re". I think there's also one case where the regex library is used directly so you'll want to change that call from "regex.compile" to "re.compile".

Finally, you'll want to find the file in flanker that imports cchardet (another affected library) and remove that import. Then, where you see decoder=cchardet or something similar, just replace it with "chardet". This should only be in one file.

Sorry for the hassle on those imports. I'll likely fork flanker and make the changes so this isn't a lasting issue. Let me know if you have trouble making these changes and, as mentioned, the docs for specific changes are coming soon.

Thanks for the report!

**Comment by crushallhumans** [comment]
Sweet - thanks for the tip, looks like it's working. Here are the lines/files you mentioned:

`
flanker/mime/message/headers/parsing.py:RE_HEADER = regex.compile(r'^(From |[\041-\071\073-\176]+:|[\t ])')

flanker/dkim.py:import regex as re
flanker/mime/bounce.py:import regex as re
flanker/mime/message/charsets.py:import regex as re
flanker/mime/message/headers/encodedword.py:import regex as re
flanker/mime/message/headers/parametrized.py:import regex as re
flanker/mime/message/headers/parsing.py:import regex
flanker/mime/message/headers/wrappers.py:import regex as re
flanker/mime/message/scanner.py:import regex as re

flanker/utils.py:import cchardet
flanker/utils.py:def _guess_and_convert_with(value, detector=cchardet):
`

**Comment by jordan-wright** [comment]
I've added a local modified fork of flanker which should resolve this issue.

Thanks again for reporting this, and please don't hesitate to let us know if you continue to run into issues!
