### ISSUE TITLE
Problem setting up the Dashboard

### ISSUE THREAD

**Issue by kiwiz** [duo-labs/isthislegit#23]
Hi, I tried setting up the Dashboard but got the following error:
```Traceback (most recent call last):
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 299, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/data/home/runtimes/python27_experiment/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/s~beep/boop/isthislegit.py", line 1, in <module>
    from app.report import report_blueprint
  File "/base/data/home/apps/s~beep/boop/app/report.py", line 2, in <module>
    from flanker.addresslib import address
  File "/base/data/home/apps/s~beep/boop/lib/flanker/addresslib/address.py", line 40, in <module>
    import idna
ImportError: No module named idna
```

I tried adding `idna` to the list of libraries, but that gives
```ERROR: (gcloud.app.deploy) An error occurred while parsing file: [/Users/beep/git/isthislegit/dashboard/app.yaml]
the library "idna" is not supported
  in "/Users/beep/git/isthislegit/dashboard/app.yaml", line 32, column 1
```

**Comment by jordan-wright** [comment]
Hi there!

Thanks for reporting this. I'll investigate this issue tomorrow morning and we'll figure out what's causing it.

Thanks again for reaching out!

**Comment by jordan-wright** [comment]
Have you already run:

```
pip install -r requirements.txt -t lib/
```

to install the dependencies into the `/Users/beep/git/isthislegit/dashboard/lib/` folder? If so, if you `ls` that folder, do you see the `idna` library?

**Comment by kiwiz** [comment]
Whoops, I didn't read the wiki close enough. That solved the problem, thanks!
