### ISSUE TITLE
Problem installing: "No module named _tokenizer"

### ISSUE THREAD

**Issue by glennzw** [duo-labs/isthislegit#55]
I suspect I'm being a right noob here, but I can't seem to get the app installed. I followed the installation instructions [here](https://github.com/duo-labs/isthislegit/blob/master/docs/installation.md#installing-the-dashboard), but when hitting `gcloud app browse` I end up with the following in the browser:

```
Traceback (most recent call last):
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/534e28e62871e9ae/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 240, in Handle
    handler = _config_handle.add_wsgi_middleware(self._LoadHandler())
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/534e28e62871e9ae/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 311, in _LoadHandler
    handler, path, err = LoadObject(self._handler)
  File "/base/alloc/tmpfs/dynamic_runtimes/python27g/534e28e62871e9ae/python27/python27_lib/versions/1/google/appengine/runtime/wsgi.py", line 85, in LoadObject
    obj = __import__(path[0])
  File "/base/data/home/apps/e~legit01/20200609t173630.427274252662959407/isthislegit.py", line 1, in <module>
    from app.report import report_blueprint
  File "/base/data/home/apps/e~legit01/20200609t173630.427274252662959407/app/report.py", line 2, in <module>
    from flanker.addresslib import address
  File "/base/data/home/apps/e~legit01/20200609t173630.427274252662959407/lib/flanker/addresslib/address.py", line 51, in <module>
    from flanker.addresslib.validate import (mail_exchanger_lookup,
  File "/base/data/home/apps/e~legit01/20200609t173630.427274252662959407/lib/flanker/addresslib/validate.py", line 42, in <module>
    from flanker.addresslib.plugins import aol
  File "/base/data/home/apps/e~legit01/20200609t173630.427274252662959407/lib/flanker/addresslib/plugins/aol.py", line 22, in <module>
    from flanker.addresslib.plugins._tokenizer import TokenStream
ImportError: No module named _tokenizer
```

Seems like the tokenizer module is missing, but I did run

```
pip install -r requirements.txt -t lib/
```

in the dashboard folder.

**Comment by rfdevere** [comment]
Not sure if we both pressed the wrong buttons but I am the same stage... any resolve?
